### PR TITLE
Issue #23 Bug Fix

### PR DESCRIPTION
**Pull request by danielyearwood**
@davidtheclark 
Fixing of [bug](https://github.com/davidtheclark/react-aria-tabpanel/issues/23) found when adding tabs dynamically the user is unable to focus the first tab. During fix, also found bug when the focused tab is changed via state without clicking/focusing a tab, the previously focused tab cannot be clicked. All fixes revolved around needing to set the active tab via the manager when these changes happen.

**Tab.js**
Added active flag to aid in setting the active tab in the manager.

**createManager.js**
By passing the active flag from Tab.js, now we can check this whenever a new tab is added and set appropriately. 

- Line 52 sets the default for activeTabId to whatever is already stored locally.
- Line 54 checks to see if there was anything set locally or if the new tab is active and is not the locally stored active tab, and then handles accordingly.

I also found a bug that when the active tab is controlled by the parent's state and is changed without clicking a tab, the previously active tab was not able to be clicked. I addressed this in Wrapper.js by doing the following:

**Wrapper.js**
Added componentDidUpdate and checked against the following:

- previous activeTabId still matches the manager's activeTabId
- new activeTabId (this.props.activeTabId) does not match the previous activeTabId

If these conditions are true, then that means nothing has told the manager to update the active tab, and I call the manager's activateTab method with the new activeTabId.

Please let me know if anything needs to be addressed with this approach. This is my first pull request, so any constructive feedback you have will be helpful. Thanks for letting me contribute to your project!

### CODE REVIEW

**Comment by davidtheclark** [comment]
Thanks @danielyearwood! I'm in a busy couple of weeks so it might be a bit before I can review this, but I'll circle back. 

Would you mind adding a new demo that illustrates this functionality? That will allow me to verify that it works as expected, without disrupting existing functionality.

**Comment by danielyearwood** [comment]
@davidtheclark Sure thing!

**Comment by danielyearwood** [comment]
Hey @davidtheclark thanks for the feedback. I am not sure why package-lock.json got updated. I think I have resolved the conflicts and removed whatever I did. Please let me know if I missed anything.

**Comment by danielyearwood** [comment]
@davidtheclark  Pertaining to the changelog entry, do you want me to put that under 4.3.1?

**Comment by davidtheclark** [comment]
@danielyearwood Please put it under "Head" 👍

**Comment by danielyearwood** [comment]
@davidtheclark Done! Thanks!

**Pull request merged**
