### PR TITLE
Hidden tab will be displayed none instead of null

### PR DESCRIPTION
**Pull request by adrianha**
Heres my suggestion, instead of return null, it will return element with displayed none. What do you think? @davidtheclark ?

### CODE REVIEW

**Comment by adrianha** [comment]
By the way, i cant run `npm run build`. any idea?

**Comment by davidtheclark** [comment]
Seems like this different technique works great. Have you tested it against your own stuff and verified that it works as expected and prevents the image loading problem you were having? If so, I'll merge and release.

> By the way, i cant run npm run build. any idea?

What happens? What error do you get?

**Comment by adrianha** [comment]
It works like what i expected since it wont re-mounted component inside the tab @davidtheclark. Error is about UMD related..

**Comment by davidtheclark** [comment]
> Error is about UMD related..

I still don't know what this means ... but I'll finish this update and release.

**Comment by davidtheclark** [comment]
Released in 4.2.2.

**Comment by adrianha** [comment]
Thanks @davidtheclark !

**Pull request merged**
